// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job_service.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobMessage struct {
	Command              *JobCommand      `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	StatusUpdate         *JobStatusUpdate `protobuf:"bytes,2,opt,name=status_update,json=statusUpdate,proto3" json:"status_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *JobMessage) Reset()         { *m = JobMessage{} }
func (m *JobMessage) String() string { return proto.CompactTextString(m) }
func (*JobMessage) ProtoMessage()    {}
func (*JobMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_f846ad52fd0fc9fe, []int{0}
}
func (m *JobMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobMessage.Unmarshal(m, b)
}
func (m *JobMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobMessage.Marshal(b, m, deterministic)
}
func (dst *JobMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobMessage.Merge(dst, src)
}
func (m *JobMessage) XXX_Size() int {
	return xxx_messageInfo_JobMessage.Size(m)
}
func (m *JobMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_JobMessage.DiscardUnknown(m)
}

var xxx_messageInfo_JobMessage proto.InternalMessageInfo

func (m *JobMessage) GetCommand() *JobCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *JobMessage) GetStatusUpdate() *JobStatusUpdate {
	if m != nil {
		return m.StatusUpdate
	}
	return nil
}

type JobCommand struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobCommand) Reset()         { *m = JobCommand{} }
func (m *JobCommand) String() string { return proto.CompactTextString(m) }
func (*JobCommand) ProtoMessage()    {}
func (*JobCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_f846ad52fd0fc9fe, []int{1}
}
func (m *JobCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobCommand.Unmarshal(m, b)
}
func (m *JobCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobCommand.Marshal(b, m, deterministic)
}
func (dst *JobCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobCommand.Merge(dst, src)
}
func (m *JobCommand) XXX_Size() int {
	return xxx_messageInfo_JobCommand.Size(m)
}
func (m *JobCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_JobCommand.DiscardUnknown(m)
}

var xxx_messageInfo_JobCommand proto.InternalMessageInfo

func (m *JobCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobCommand) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type JobCommandResult struct {
	JobId                uint64   `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobCommandResult) Reset()         { *m = JobCommandResult{} }
func (m *JobCommandResult) String() string { return proto.CompactTextString(m) }
func (*JobCommandResult) ProtoMessage()    {}
func (*JobCommandResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_f846ad52fd0fc9fe, []int{2}
}
func (m *JobCommandResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobCommandResult.Unmarshal(m, b)
}
func (m *JobCommandResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobCommandResult.Marshal(b, m, deterministic)
}
func (dst *JobCommandResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobCommandResult.Merge(dst, src)
}
func (m *JobCommandResult) XXX_Size() int {
	return xxx_messageInfo_JobCommandResult.Size(m)
}
func (m *JobCommandResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JobCommandResult.DiscardUnknown(m)
}

var xxx_messageInfo_JobCommandResult proto.InternalMessageInfo

func (m *JobCommandResult) GetJobId() uint64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type JobStatusRequest struct {
	JobId                uint64   `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatusRequest) Reset()         { *m = JobStatusRequest{} }
func (m *JobStatusRequest) String() string { return proto.CompactTextString(m) }
func (*JobStatusRequest) ProtoMessage()    {}
func (*JobStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_f846ad52fd0fc9fe, []int{3}
}
func (m *JobStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatusRequest.Unmarshal(m, b)
}
func (m *JobStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatusRequest.Marshal(b, m, deterministic)
}
func (dst *JobStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatusRequest.Merge(dst, src)
}
func (m *JobStatusRequest) XXX_Size() int {
	return xxx_messageInfo_JobStatusRequest.Size(m)
}
func (m *JobStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatusRequest proto.InternalMessageInfo

func (m *JobStatusRequest) GetJobId() uint64 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type JobStatus struct {
	CommandName          string   `protobuf:"bytes,1,opt,name=command_name,json=commandName,proto3" json:"command_name,omitempty"`
	CommandArgs          string   `protobuf:"bytes,2,opt,name=command_args,json=commandArgs,proto3" json:"command_args,omitempty"`
	StdOut               string   `protobuf:"bytes,3,opt,name=std_out,json=stdOut,proto3" json:"std_out,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatus) Reset()         { *m = JobStatus{} }
func (m *JobStatus) String() string { return proto.CompactTextString(m) }
func (*JobStatus) ProtoMessage()    {}
func (*JobStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_f846ad52fd0fc9fe, []int{4}
}
func (m *JobStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatus.Unmarshal(m, b)
}
func (m *JobStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatus.Marshal(b, m, deterministic)
}
func (dst *JobStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatus.Merge(dst, src)
}
func (m *JobStatus) XXX_Size() int {
	return xxx_messageInfo_JobStatus.Size(m)
}
func (m *JobStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatus.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatus proto.InternalMessageInfo

func (m *JobStatus) GetCommandName() string {
	if m != nil {
		return m.CommandName
	}
	return ""
}

func (m *JobStatus) GetCommandArgs() string {
	if m != nil {
		return m.CommandArgs
	}
	return ""
}

func (m *JobStatus) GetStdOut() string {
	if m != nil {
		return m.StdOut
	}
	return ""
}

type JobStatusUpdate struct {
	StdinLine            string   `protobuf:"bytes,1,opt,name=stdin_line,json=stdinLine,proto3" json:"stdin_line,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatusUpdate) Reset()         { *m = JobStatusUpdate{} }
func (m *JobStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*JobStatusUpdate) ProtoMessage()    {}
func (*JobStatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_f846ad52fd0fc9fe, []int{5}
}
func (m *JobStatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatusUpdate.Unmarshal(m, b)
}
func (m *JobStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatusUpdate.Marshal(b, m, deterministic)
}
func (dst *JobStatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatusUpdate.Merge(dst, src)
}
func (m *JobStatusUpdate) XXX_Size() int {
	return xxx_messageInfo_JobStatusUpdate.Size(m)
}
func (m *JobStatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatusUpdate proto.InternalMessageInfo

func (m *JobStatusUpdate) GetStdinLine() string {
	if m != nil {
		return m.StdinLine
	}
	return ""
}

type JobStatusUpdatesResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatusUpdatesResult) Reset()         { *m = JobStatusUpdatesResult{} }
func (m *JobStatusUpdatesResult) String() string { return proto.CompactTextString(m) }
func (*JobStatusUpdatesResult) ProtoMessage()    {}
func (*JobStatusUpdatesResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_f846ad52fd0fc9fe, []int{6}
}
func (m *JobStatusUpdatesResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatusUpdatesResult.Unmarshal(m, b)
}
func (m *JobStatusUpdatesResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatusUpdatesResult.Marshal(b, m, deterministic)
}
func (dst *JobStatusUpdatesResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatusUpdatesResult.Merge(dst, src)
}
func (m *JobStatusUpdatesResult) XXX_Size() int {
	return xxx_messageInfo_JobStatusUpdatesResult.Size(m)
}
func (m *JobStatusUpdatesResult) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatusUpdatesResult.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatusUpdatesResult proto.InternalMessageInfo

func init() {
	proto.RegisterType((*JobMessage)(nil), "rpc.JobMessage")
	proto.RegisterType((*JobCommand)(nil), "rpc.JobCommand")
	proto.RegisterType((*JobCommandResult)(nil), "rpc.JobCommandResult")
	proto.RegisterType((*JobStatusRequest)(nil), "rpc.JobStatusRequest")
	proto.RegisterType((*JobStatus)(nil), "rpc.JobStatus")
	proto.RegisterType((*JobStatusUpdate)(nil), "rpc.JobStatusUpdate")
	proto.RegisterType((*JobStatusUpdatesResult)(nil), "rpc.JobStatusUpdatesResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobServiceClient interface {
	// A Bidirectional streaming RPC.
	// rpc JobMessages(stream JobMessage) returns (stream JobMessage) {}
	ScheduleCommand(ctx context.Context, in *JobCommand, opts ...grpc.CallOption) (JobService_ScheduleCommandClient, error)
}

type jobServiceClient struct {
	cc *grpc.ClientConn
}

func NewJobServiceClient(cc *grpc.ClientConn) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) ScheduleCommand(ctx context.Context, in *JobCommand, opts ...grpc.CallOption) (JobService_ScheduleCommandClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JobService_serviceDesc.Streams[0], "/rpc.JobService/ScheduleCommand", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobServiceScheduleCommandClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JobService_ScheduleCommandClient interface {
	Recv() (*JobStatusUpdate, error)
	grpc.ClientStream
}

type jobServiceScheduleCommandClient struct {
	grpc.ClientStream
}

func (x *jobServiceScheduleCommandClient) Recv() (*JobStatusUpdate, error) {
	m := new(JobStatusUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// JobServiceServer is the server API for JobService service.
type JobServiceServer interface {
	// A Bidirectional streaming RPC.
	// rpc JobMessages(stream JobMessage) returns (stream JobMessage) {}
	ScheduleCommand(*JobCommand, JobService_ScheduleCommandServer) error
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_ScheduleCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobCommand)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobServiceServer).ScheduleCommand(m, &jobServiceScheduleCommandServer{stream})
}

type JobService_ScheduleCommandServer interface {
	Send(*JobStatusUpdate) error
	grpc.ServerStream
}

type jobServiceScheduleCommandServer struct {
	grpc.ServerStream
}

func (x *jobServiceScheduleCommandServer) Send(m *JobStatusUpdate) error {
	return x.ServerStream.SendMsg(m)
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScheduleCommand",
			Handler:       _JobService_ScheduleCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "job_service.proto",
}

// DispatcherServiceClient is the client API for DispatcherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DispatcherServiceClient interface {
	StreamJobStatus(ctx context.Context, opts ...grpc.CallOption) (DispatcherService_StreamJobStatusClient, error)
}

type dispatcherServiceClient struct {
	cc *grpc.ClientConn
}

func NewDispatcherServiceClient(cc *grpc.ClientConn) DispatcherServiceClient {
	return &dispatcherServiceClient{cc}
}

func (c *dispatcherServiceClient) StreamJobStatus(ctx context.Context, opts ...grpc.CallOption) (DispatcherService_StreamJobStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DispatcherService_serviceDesc.Streams[0], "/rpc.DispatcherService/StreamJobStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &dispatcherServiceStreamJobStatusClient{stream}
	return x, nil
}

type DispatcherService_StreamJobStatusClient interface {
	Send(*JobStatusUpdate) error
	CloseAndRecv() (*JobStatusUpdatesResult, error)
	grpc.ClientStream
}

type dispatcherServiceStreamJobStatusClient struct {
	grpc.ClientStream
}

func (x *dispatcherServiceStreamJobStatusClient) Send(m *JobStatusUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dispatcherServiceStreamJobStatusClient) CloseAndRecv() (*JobStatusUpdatesResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(JobStatusUpdatesResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DispatcherServiceServer is the server API for DispatcherService service.
type DispatcherServiceServer interface {
	StreamJobStatus(DispatcherService_StreamJobStatusServer) error
}

func RegisterDispatcherServiceServer(s *grpc.Server, srv DispatcherServiceServer) {
	s.RegisterService(&_DispatcherService_serviceDesc, srv)
}

func _DispatcherService_StreamJobStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DispatcherServiceServer).StreamJobStatus(&dispatcherServiceStreamJobStatusServer{stream})
}

type DispatcherService_StreamJobStatusServer interface {
	SendAndClose(*JobStatusUpdatesResult) error
	Recv() (*JobStatusUpdate, error)
	grpc.ServerStream
}

type dispatcherServiceStreamJobStatusServer struct {
	grpc.ServerStream
}

func (x *dispatcherServiceStreamJobStatusServer) SendAndClose(m *JobStatusUpdatesResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dispatcherServiceStreamJobStatusServer) Recv() (*JobStatusUpdate, error) {
	m := new(JobStatusUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DispatcherService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.DispatcherService",
	HandlerType: (*DispatcherServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamJobStatus",
			Handler:       _DispatcherService_StreamJobStatus_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "job_service.proto",
}

func init() { proto.RegisterFile("job_service.proto", fileDescriptor_job_service_f846ad52fd0fc9fe) }

var fileDescriptor_job_service_f846ad52fd0fc9fe = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xcd, 0x4b, 0xfb, 0x40,
	0x10, 0x6d, 0x7e, 0xed, 0xaf, 0x25, 0xd3, 0x4a, 0xec, 0xe2, 0x47, 0xa8, 0x08, 0x9a, 0x53, 0x7b,
	0x29, 0xa5, 0x7a, 0x11, 0xbc, 0x88, 0x1e, 0xb4, 0xf8, 0x01, 0x09, 0x1e, 0x25, 0x6c, 0x92, 0xa1,
	0x4d, 0x69, 0xb2, 0x71, 0x67, 0xd7, 0xbf, 0x5f, 0xba, 0x49, 0x34, 0x94, 0x7a, 0xdb, 0xbc, 0x79,
	0xf3, 0xe6, 0xcd, 0x9b, 0xc0, 0x70, 0x2d, 0xa2, 0x90, 0x50, 0x7e, 0xa5, 0x31, 0x4e, 0x0b, 0x29,
	0x94, 0x60, 0x6d, 0x59, 0xc4, 0x9e, 0x04, 0x58, 0x88, 0xe8, 0x05, 0x89, 0xf8, 0x12, 0xd9, 0x04,
	0x7a, 0xb1, 0xc8, 0x32, 0x9e, 0x27, 0xae, 0x75, 0x61, 0x8d, 0xfb, 0x73, 0x67, 0x2a, 0x8b, 0x78,
	0xba, 0x10, 0xd1, 0x7d, 0x09, 0xfb, 0x75, 0x9d, 0xdd, 0xc0, 0x01, 0x29, 0xae, 0x34, 0x85, 0xba,
	0x48, 0xb8, 0x42, 0xf7, 0x9f, 0x69, 0x38, 0xaa, 0x1b, 0x02, 0x53, 0x7c, 0x37, 0x35, 0x7f, 0x40,
	0x8d, 0x2f, 0xef, 0xda, 0xcc, 0xac, 0x14, 0x19, 0x83, 0x4e, 0xce, 0x33, 0x34, 0x03, 0x6d, 0xdf,
	0xbc, 0xb7, 0x18, 0x97, 0x4b, 0x32, 0x9a, 0xb6, 0x6f, 0xde, 0xde, 0x04, 0x0e, 0x1b, 0x3e, 0x90,
	0xf4, 0x46, 0xb1, 0x63, 0xe8, 0x6e, 0xf7, 0x4a, 0x4b, 0xbb, 0x1d, 0xff, 0xff, 0x5a, 0x44, 0x4f,
	0x49, 0x45, 0x2d, 0x1d, 0xf8, 0xf8, 0xa9, 0x91, 0xfe, 0xa4, 0xae, 0xc1, 0xfe, 0xa1, 0xb2, 0x4b,
	0x18, 0x54, 0xeb, 0x85, 0x0d, 0x4b, 0xfd, 0x0a, 0x7b, 0xdd, 0x3a, 0x6b, 0x50, 0x1a, 0x0e, 0x6b,
	0xca, 0x9d, 0x5c, 0x12, 0x3b, 0x85, 0x1e, 0xa9, 0x24, 0x14, 0x5a, 0xb9, 0x6d, 0x53, 0xed, 0x92,
	0x4a, 0xde, 0xb4, 0xf2, 0x66, 0xe0, 0xec, 0x04, 0xc3, 0xce, 0x01, 0x48, 0x25, 0x69, 0x1e, 0x6e,
	0xd2, 0xbc, 0x9e, 0x67, 0x1b, 0xe4, 0x39, 0xcd, 0xd1, 0x73, 0xe1, 0x64, 0xa7, 0x83, 0xca, 0xcd,
	0xe7, 0x0b, 0x93, 0x61, 0x50, 0x1e, 0x94, 0xdd, 0x82, 0x13, 0xc4, 0x2b, 0x4c, 0xf4, 0x06, 0xeb,
	0x58, 0x77, 0x2f, 0x37, 0xda, 0x7b, 0x19, 0xaf, 0x35, 0xb3, 0xe6, 0x1f, 0x30, 0x7c, 0x48, 0xa9,
	0xe0, 0x2a, 0x5e, 0xa1, 0xac, 0x25, 0x1f, 0xc1, 0x09, 0x94, 0x44, 0x9e, 0xfd, 0xc6, 0xb3, 0x57,
	0x61, 0x74, 0xb6, 0x0f, 0xad, 0x6c, 0x7a, 0xad, 0xb1, 0x15, 0x75, 0xcd, 0xef, 0x76, 0xf5, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x1c, 0x2a, 0xb5, 0x59, 0x83, 0x02, 0x00, 0x00,
}
