// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job_service.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JobCommand struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobCommand) Reset()         { *m = JobCommand{} }
func (m *JobCommand) String() string { return proto.CompactTextString(m) }
func (*JobCommand) ProtoMessage()    {}
func (*JobCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_51596ec0dfd271d2, []int{0}
}
func (m *JobCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobCommand.Unmarshal(m, b)
}
func (m *JobCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobCommand.Marshal(b, m, deterministic)
}
func (dst *JobCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobCommand.Merge(dst, src)
}
func (m *JobCommand) XXX_Size() int {
	return xxx_messageInfo_JobCommand.Size(m)
}
func (m *JobCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_JobCommand.DiscardUnknown(m)
}

var xxx_messageInfo_JobCommand proto.InternalMessageInfo

func (m *JobCommand) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobCommand) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type JobStatusUpdate struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	PID                  int64    `protobuf:"varint,2,opt,name=PID,proto3" json:"PID,omitempty"`
	Complete             bool     `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	Exit                 int64    `protobuf:"varint,4,opt,name=exit,proto3" json:"exit,omitempty"`
	StartTs              int64    `protobuf:"varint,5,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	StopTs               int64    `protobuf:"varint,6,opt,name=stop_ts,json=stopTs,proto3" json:"stop_ts,omitempty"`
	Runtime              float32  `protobuf:"fixed32,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Stdout               string   `protobuf:"bytes,8,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr               string   `protobuf:"bytes,9,opt,name=stderr,proto3" json:"stderr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobStatusUpdate) Reset()         { *m = JobStatusUpdate{} }
func (m *JobStatusUpdate) String() string { return proto.CompactTextString(m) }
func (*JobStatusUpdate) ProtoMessage()    {}
func (*JobStatusUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_51596ec0dfd271d2, []int{1}
}
func (m *JobStatusUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobStatusUpdate.Unmarshal(m, b)
}
func (m *JobStatusUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobStatusUpdate.Marshal(b, m, deterministic)
}
func (dst *JobStatusUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobStatusUpdate.Merge(dst, src)
}
func (m *JobStatusUpdate) XXX_Size() int {
	return xxx_messageInfo_JobStatusUpdate.Size(m)
}
func (m *JobStatusUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_JobStatusUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_JobStatusUpdate proto.InternalMessageInfo

func (m *JobStatusUpdate) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

func (m *JobStatusUpdate) GetPID() int64 {
	if m != nil {
		return m.PID
	}
	return 0
}

func (m *JobStatusUpdate) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

func (m *JobStatusUpdate) GetExit() int64 {
	if m != nil {
		return m.Exit
	}
	return 0
}

func (m *JobStatusUpdate) GetStartTs() int64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *JobStatusUpdate) GetStopTs() int64 {
	if m != nil {
		return m.StopTs
	}
	return 0
}

func (m *JobStatusUpdate) GetRuntime() float32 {
	if m != nil {
		return m.Runtime
	}
	return 0
}

func (m *JobStatusUpdate) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *JobStatusUpdate) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

type HeartbeatPing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatPing) Reset()         { *m = HeartbeatPing{} }
func (m *HeartbeatPing) String() string { return proto.CompactTextString(m) }
func (*HeartbeatPing) ProtoMessage()    {}
func (*HeartbeatPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_51596ec0dfd271d2, []int{2}
}
func (m *HeartbeatPing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatPing.Unmarshal(m, b)
}
func (m *HeartbeatPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatPing.Marshal(b, m, deterministic)
}
func (dst *HeartbeatPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatPing.Merge(dst, src)
}
func (m *HeartbeatPing) XXX_Size() int {
	return xxx_messageInfo_HeartbeatPing.Size(m)
}
func (m *HeartbeatPing) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatPing.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatPing proto.InternalMessageInfo

type HeartbeatPong struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatPong) Reset()         { *m = HeartbeatPong{} }
func (m *HeartbeatPong) String() string { return proto.CompactTextString(m) }
func (*HeartbeatPong) ProtoMessage()    {}
func (*HeartbeatPong) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_service_51596ec0dfd271d2, []int{3}
}
func (m *HeartbeatPong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatPong.Unmarshal(m, b)
}
func (m *HeartbeatPong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatPong.Marshal(b, m, deterministic)
}
func (dst *HeartbeatPong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatPong.Merge(dst, src)
}
func (m *HeartbeatPong) XXX_Size() int {
	return xxx_messageInfo_HeartbeatPong.Size(m)
}
func (m *HeartbeatPong) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatPong.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatPong proto.InternalMessageInfo

func init() {
	proto.RegisterType((*JobCommand)(nil), "rpc.JobCommand")
	proto.RegisterType((*JobStatusUpdate)(nil), "rpc.JobStatusUpdate")
	proto.RegisterType((*HeartbeatPing)(nil), "rpc.HeartbeatPing")
	proto.RegisterType((*HeartbeatPong)(nil), "rpc.HeartbeatPong")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobServiceClient is the client API for JobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobServiceClient interface {
	ScheduleCommand(ctx context.Context, in *JobCommand, opts ...grpc.CallOption) (JobService_ScheduleCommandClient, error)
	Heartbeat(ctx context.Context, in *HeartbeatPing, opts ...grpc.CallOption) (*HeartbeatPong, error)
}

type jobServiceClient struct {
	cc *grpc.ClientConn
}

func NewJobServiceClient(cc *grpc.ClientConn) JobServiceClient {
	return &jobServiceClient{cc}
}

func (c *jobServiceClient) ScheduleCommand(ctx context.Context, in *JobCommand, opts ...grpc.CallOption) (JobService_ScheduleCommandClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JobService_serviceDesc.Streams[0], "/rpc.JobService/ScheduleCommand", opts...)
	if err != nil {
		return nil, err
	}
	x := &jobServiceScheduleCommandClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JobService_ScheduleCommandClient interface {
	Recv() (*JobStatusUpdate, error)
	grpc.ClientStream
}

type jobServiceScheduleCommandClient struct {
	grpc.ClientStream
}

func (x *jobServiceScheduleCommandClient) Recv() (*JobStatusUpdate, error) {
	m := new(JobStatusUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jobServiceClient) Heartbeat(ctx context.Context, in *HeartbeatPing, opts ...grpc.CallOption) (*HeartbeatPong, error) {
	out := new(HeartbeatPong)
	err := c.cc.Invoke(ctx, "/rpc.JobService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServiceServer is the server API for JobService service.
type JobServiceServer interface {
	ScheduleCommand(*JobCommand, JobService_ScheduleCommandServer) error
	Heartbeat(context.Context, *HeartbeatPing) (*HeartbeatPong, error)
}

func RegisterJobServiceServer(s *grpc.Server, srv JobServiceServer) {
	s.RegisterService(&_JobService_serviceDesc, srv)
}

func _JobService_ScheduleCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JobCommand)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobServiceServer).ScheduleCommand(m, &jobServiceScheduleCommandServer{stream})
}

type JobService_ScheduleCommandServer interface {
	Send(*JobStatusUpdate) error
	grpc.ServerStream
}

type jobServiceScheduleCommandServer struct {
	grpc.ServerStream
}

func (x *jobServiceScheduleCommandServer) Send(m *JobStatusUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _JobService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatPing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.JobService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServiceServer).Heartbeat(ctx, req.(*HeartbeatPing))
	}
	return interceptor(ctx, in, info, handler)
}

var _JobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.JobService",
	HandlerType: (*JobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _JobService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScheduleCommand",
			Handler:       _JobService_ScheduleCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "job_service.proto",
}

func init() { proto.RegisterFile("job_service.proto", fileDescriptor_job_service_51596ec0dfd271d2) }

var fileDescriptor_job_service_51596ec0dfd271d2 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x3f, 0x4f, 0xe3, 0x40,
	0x10, 0xc5, 0xb3, 0x71, 0xce, 0x76, 0x46, 0x3a, 0xf9, 0x6e, 0x74, 0x3a, 0x96, 0x54, 0x91, 0xab,
	0x54, 0x11, 0xe2, 0x4f, 0x47, 0x07, 0x05, 0xa4, 0x8a, 0x9c, 0x50, 0x47, 0x6b, 0x7b, 0x64, 0x8c,
	0x62, 0xaf, 0xb5, 0x3b, 0x46, 0xb4, 0x7c, 0x56, 0xbe, 0x08, 0xda, 0xcd, 0x1f, 0x08, 0xdd, 0x7b,
	0xbf, 0x99, 0xd9, 0x59, 0xbd, 0x81, 0xbf, 0x2f, 0x3a, 0xdf, 0x58, 0x32, 0xaf, 0x75, 0x41, 0xf3,
	0xce, 0x68, 0xd6, 0x18, 0x98, 0xae, 0x48, 0xaf, 0x01, 0x16, 0x3a, 0xbf, 0xd3, 0x4d, 0xa3, 0xda,
	0x12, 0x11, 0x46, 0xad, 0x6a, 0x48, 0x8a, 0xa9, 0x98, 0x8d, 0x33, 0xaf, 0x1d, 0x53, 0xa6, 0xb2,
	0x72, 0xb8, 0x63, 0x4e, 0xa7, 0x1f, 0x02, 0x92, 0x85, 0xce, 0x57, 0xac, 0xb8, 0xb7, 0x4f, 0x5d,
	0xa9, 0x98, 0xf0, 0x0f, 0x04, 0x45, 0x53, 0xee, 0x47, 0x9d, 0x74, 0x64, 0xf9, 0x78, 0xef, 0x07,
	0x83, 0xcc, 0x49, 0x9c, 0x40, 0x5c, 0xe8, 0xa6, 0xdb, 0x12, 0x93, 0x0c, 0xa6, 0x62, 0x16, 0x67,
	0x47, 0xef, 0xf6, 0xd0, 0x5b, 0xcd, 0x72, 0xe4, 0xdb, 0xbd, 0xc6, 0x73, 0x88, 0x2d, 0x2b, 0xc3,
	0x1b, 0xb6, 0xf2, 0x97, 0xe7, 0x91, 0xf7, 0x6b, 0x8b, 0x67, 0x10, 0x59, 0xd6, 0x9d, 0xab, 0x84,
	0xbe, 0x12, 0x3a, 0xbb, 0xb6, 0x28, 0x21, 0x32, 0x7d, 0xcb, 0x75, 0x43, 0x32, 0x9a, 0x8a, 0xd9,
	0x30, 0x3b, 0x58, 0xfc, 0x0f, 0xa1, 0xe5, 0x52, 0xf7, 0x2c, 0x63, 0xff, 0xc9, 0xbd, 0xdb, 0x73,
	0x32, 0x46, 0x8e, 0x8f, 0x9c, 0x8c, 0x49, 0x13, 0xf8, 0xfd, 0x40, 0xca, 0x70, 0x4e, 0x8a, 0x97,
	0x75, 0x5b, 0x9d, 0x02, 0xdd, 0x56, 0x97, 0xef, 0xc2, 0xc7, 0xb7, 0xda, 0xe5, 0x8a, 0xb7, 0x90,
	0xac, 0x8a, 0x67, 0x2a, 0xfb, 0x2d, 0x1d, 0x12, 0x4d, 0xe6, 0xa6, 0x2b, 0xe6, 0x5f, 0x11, 0x4f,
	0xfe, 0x1d, 0xc0, 0xf7, 0xf0, 0xd2, 0xc1, 0x85, 0xc0, 0x1b, 0x18, 0x1f, 0x5f, 0x47, 0xf4, 0x6d,
	0x27, 0xeb, 0x27, 0x3f, 0x99, 0x6e, 0xab, 0x74, 0x90, 0x87, 0xfe, 0x9a, 0x57, 0x9f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x16, 0x73, 0x47, 0x92, 0xe2, 0x01, 0x00, 0x00,
}
